version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: task_management_development
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    stdin_open: true
    platform: linux/x86_64
    tty: true
    build: .
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  db_data:
  bundle_cache:
