services:
  app:
    container_name: notifications_service
    stdin_open: true
    platform: linux/x86_64
    tty: true
    build: .
    command: sh entrypoint.sh
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "${PORT:-3300}:3000"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    name: app-network
    external: true

volumes:
  bundle_cache:
